excluded:
  - Example/MPSinglePlayer.xcodeproj/
  - Example/MPSinglePlayer.xcworkspace/
  - Example/Pods
  - scripts
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - object_literal
  - prohibited_super_call
  - force_unwrapping
  - force_try
  - force_cast
disabled_rules:
  - line_length
  - todo
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning
force_try: error
force_unwrapping: error

file_length:
  warning: 900
  error: 1200
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
variable_name:
  max_length:
    warning: 55
    error: 60
  excluded:
    - url
type_body_length:
   warning: 300
   error: 900
function_body_length:
   warning: 50
   error: 100
cyclomatic_complexity:
   warning: 10
   error: 15

